#!/bin/bash
# Author:      Matthew White <matthew.white@telefonica.com>
# Description: Sets AWS Credentials 
# Requires:    git, bash
# Compatibility: currently only compatible with Linux & Apple Mac
# Version: 0.1
# Usage ./create_aws_creds.sh

AWS_DIRECTORY=${HOME}/.aws

#Test is AWS Credentials already exist if not create the directory
if [ -d ${AWS_DIRECTORY} ]
	then
		cd ${AWS_DIRECTORY}
	else
		mkdir ${AWS_DIRECTORY}
fi

#Ask user for their AWS Credentials and trim any extra spaces
echo -n "Please enter your AWS Access Key [ENTER] "
	read AWS_ACCESS_KEY
		AWS_ACCESS_KEY=`echo $AWS_ACCESS_KEY | awk '{print $1}'`
echo -n "Please enter your AWS Secret [ENTER] "
	read AWS_SECRET
		AWS_SECRET=`echo $AWS_ACCESS_KEY | awk '{print $1}'`
echo

#Store Credentials in variables
AWS_DETAILS="[default]
aws_access_key_id = ${AWS_ACCESS_KEY}
aws_secret_access_key = ${AWS_SECRET}"

#Print Credentials to file
echo "${AWS_DETAILS}" > credentials